server {
    listen 80;
    
    # Ocultar la versión de Nginx en las cabeceras HTTP por seguridad
    server_tokens off;
    
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Ocultar /admin devolviendo 403 para evitar enumeración y confirmación
    location ^~ /admin {
        return 403;
    }

    # Bloque principal
    location / {
        # Si el archivo existe lo sirve, si no, lo manda a la gestión de 404
        try_files $uri $uri/ @notfound;
    }

    # Para rutas de SPA inválidas, retornamos 404 explícito
    location @notfound {
        return 404;
    }

    # Interceptar el error 404 y cargar el 404.html (que contiene la SPA)
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
